version: '3.1'

services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: allister_kays
      MYSQL_ROOT_PASSWORD: epicodus
  db_test:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: allister_kays_test
      MYSQL_ROOT_PASSWORD: epicodus